### ISSUE TITLE
diff-hl-mode doesn't show anything

### ISSUE THREAD

**Issue by gred7** [doomemacs/snippets#113]
### What were you expecting?

my setup:
GNU Emacs     v29.4            nil
Doom core     v3.0.0-pre       HEAD -> master 2b0013db 2024-11-19 01:04:41 -0500
Doom modules  v24.12.0-pre     HEAD -> master 2b0013db 2024-11-19 01:04:41 -0500

changing file under git  control and writing it to disk. i expect changed lines  to be marked on the fringe

### What actually happened?

just shows empty fringe.

### Steps to reproduce

open file that is under control of the git
change some lines

### Operating system

OpenBSD-current

### Emacs version

Emacs 29.4 

### Installed commit of doom-snippets

2b0013db

**Comment by hlissner** [comment]
I assume you meant to post this in [doomemacs/doomemacs](https://github.com/doomemacs/doomemacs/issues), because this issue has nothing to do with this repo. Please repost this there, but please don't repost it verbatim; [fill out the issue template there as best you can](https://github.com/doomemacs/doomemacs/issues/new?template=bug_report.yml), including your `M-x doom/info` and a link to your personal config.

**Comment by gred7** [comment]
generated  Nov 20, 2024 00:05:53
system     Unknown GENERIC.MP#399 OpenBSD 7.6 amd64 x
emacs      29.4 EMACSDIR=~/.config/emacs/ EMACS=/usr/local/bin/emacs
doom       3.0.0-pre PROFILE=_default@0 HEAD -> master 2b0013db 2024-11-19 01:04:41
           -0500 ~/.config/doom/
shell      /usr/local/bin/zsh
features   CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LCMS2
           LIBOTF LIBXML2 M17N_FLT MODULES NOTIFY KQUEUE PDUMPER PNG RSVG SQLITE3
           THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM
           GTK3 ZLIB
traits     gui server-running envvar-file
modules    :config use-package :completion (corfu +orderless) vertico :ui doom
           doom-dashboard hl-todo modeline ophints (popup +defaults) tabs treemacs
           (vc-gutter +pretty) vi-tilde-fringe workspaces :editor (evil +everywhere)
           file-templates fold snippets :emacs dired electric undo vc :checkers syntax
           :tools ansible docker (eval +overlay) lookup magit terraform :lang (cc
           +lsp) emacs-lisp markdown org php python sh yaml :config (default +bindings
           +smartparens)
packages   (diff-hl)

my config is basically stock for now, except these lines:
 
(setq projectile-project-search-path '(("~/projects" . 1) ))

(setq tab-always-indent 'complete)

(use-package! diff-hl
:hook ((prog-mode . diff-hl-mode)
(text-mode . diff-hl-mode)
(dired-mode . diff-hl-dired-mode))
:config
(diff-hl-flydiff-mode)
(diff-hl-margin-mode))
