### ISSUE TITLE
`org-mode/chinese_...` snippets evaluation error

### ISSUE THREAD

**Issue by dschrempf** [doomemacs/snippets#81]
### What did you expect to happen?

Snippets do not through evaluation errors.

### What actually happened?

`org-mode/chinese_dollar` and `org-mode/chinese_link` throw:

```
eval: Symbol’s function definition is void: fcitx--deactivate
```

### Steps to reproduce

1. Open an Org mode buffer.
2. Insert the mentioned snippets.

### Package commit

28a929663bc56f523bef5f0c8a364258b992f02c

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
