### ISSUE TITLE
[go] spurious space when using `const` snippet in go-mode

### ISSUE THREAD

**Issue by yesudeep** [doomemacs/snippets#93]
### What were you expecting?

```
const [name] [type] = [value]
```

### What actually happened?

```
const [name][ type] = [value]
```

The current snippet makes it stick to the const name. The space should not be part of the field.

### Steps to reproduce

1. type `const`
2. press `tab`
3. examine expansion

### Operating system

Fedora Linux 37 amd64

### Emacs version

Emacs 30.0.50 (master) w/ native-comp

### Installed commit of doom-snippets

not sure, but bug is present in head

**Comment by hlissner** [comment]
Sorry for taking so long to get to this. As of 5bcbd80 this should be resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
